syntax = "proto3";

package entur.kittum.v1;

import "entur/http/v1/failure.proto";
import "entur/validation/v1/owner.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";

option go_package = "github.com/entur/validation-core/gen/entur/kittum/v1;kittumv1";
option java_multiple_files = true;
option java_package = "no.entur.kittum.proto.v1";

// The gRPC service to view and administrate owners.
service OwnerService {
  option (google.api.default_host) = "kittum.entur.io";

  // List all existing owners.
  rpc ListOwners(ListOwnersRequest) returns (ListOwnersResponse) {
    option (google.api.http) = {get: "/v1/owners"};
    option (gnostic.openapi.v3.operation) = {summary: "List all existing owners."};
  }

  // Get one owner by its id.
  rpc GetOwner(GetOwnerRequest) returns (entur.validation.v1.Owner) {
    option (google.api.http) = {get: "/v1/owners/{id}"};
    option (gnostic.openapi.v3.operation) = {summary: "Get one owner by its id."};
    option (entur.http.v1.failure) = {
      code: "404"
      description: "No owner exists with the given id."
    };
  }
}

// Request for ListOwners.
message ListOwnersRequest {}

// Response for ListOwners.
message ListOwnersResponse {
  // All existing owners.
  repeated entur.validation.v1.Owner items = 1;
}

// Request for GetOwner.
message GetOwnerRequest {
  // The database id of the owner to lookup.
  int32 id = 1 [
    (google.api.field_behavior) = REQUIRED,
    (gnostic.openapi.v3.property) = {
      example: {yaml: "1"}
    }
  ];
}
